From f5dda9bc4ff5e3b6f2736a90dd51f3bd7c1209da Mon Sep 17 00:00:00 2001
From: Cristi√°n Maureira-Fredes <Cristian.Maureira-Fredes@qt.io>
Date: Tue, 01 Apr 2025 15:37:48 +0200
Subject: [PATCH] qtasyncio: fix f-string quotation

Considering we still support old Python versions,
we cannot have the same quotation mark for f-string and for
variables within the f-string.

Fixes: PYSIDE-3068
Pick-to: 6.8 6.9 6.9.0
Change-Id: Ie9f1ed91f1a1965631bc71f35600780bb4f00603
---

diff --git a/sources/pyside6/PySide6/QtAsyncio/events.py b/sources/pyside6/PySide6/QtAsyncio/events.py
index f99b601..6b51e11 100644
--- a/sources/pyside6/PySide6/QtAsyncio/events.py
+++ b/sources/pyside6/PySide6/QtAsyncio/events.py
@@ -598,7 +598,7 @@
     def default_exception_handler(self, context: dict[str, Any]) -> None:
         # TODO
         if context["message"]:
-            print(f"{context["message"]} from task {context["task"]._name},"+
+            print(f"{context['message']} from task {context['task']._name},"+
                     "read the following traceback:")
             print(context["traceback"])
 
